### ISSUE TITLE
luaposix

### ISSUE THREAD

**Issue by graugans** [seife/meta-neutrino-mp#1]
I had some qa issues with [luaposix](https://github.com/seife/meta-neutrino-mp/blob/master/recipes-local/lua/luaposix.inc#L14) in another project where is lend your luaposix recipes.

```
ERROR: This autoconf log indicates errors, it looked at host include and/or library paths while determining system capabilities.
Rerun configure task after fixing this. The path was '/data/o3d3xx/eldk-dzu/build/tmp/work/armv7a-vfp-neon-linux-gnueabi/luaposix-31-r1/luaposix-release-v31'
ERROR: Function failed: do_qa_configure
ERROR: Logfile of failure stored in: /data/o3d3xx/eldk-dzu/build/tmp/work/armv7a-vfp-neon-linux-gnueabi/luaposix-31-r1/temp/log.do_configure.30141
ERROR: Task 5 (/data/o3d3xx/eldk-dzu/meta-goldeneye/recipes-devtools/lua/luaposix_31.bb, do_configure) failed with exit code '1'
NOTE: Tasks Summary: Attempted 1061 tasks of which 1060 didn't need to be rerun and 1 failed.
No currently running tasks (707 of 1069)
```

Maybe this issue is caused by locally installed  lua-5.2 headers. I fixed this by adding LUA_INCLUDE to EXTRA_OECONF. 

```
-EXTRA_OECONF += "--datadir=${datadir}/lua/5.2 --libdir=${libdir}/lua/5.2"
+EXTRA_OECONF += "--datadir=${datadir}/lua/5.2 --libdir=${libdir}/lua/5.2 \
+                 'LUA_INCLUDE=-I${STAGING_DIR_TARGET}${includedir}/lua5.2' \
+"
```

**Comment by seife** [comment]
How do you trigger this error? I have lua-devel installed in the host system and did not see this.
Do I need to enable any special QA steps?
(Disclaimer: tested with poky branch dizzy, machine raspberrypi2)

**Comment by graugans** [comment]
It is a bit strange and maybe you can just ignore this. We had no problems on regular builds but as we started to build our toolchains with -c populate_sdk the error occurred. Maybe I find the time and check this with a more recent version of yocto.
